### ISSUE TITLE
Looks like dyn_optics.rs needs to be added?

### ISSUE THREAD

**Issue by windwardly** [TOETOE55/lens-rs#7]
When I build I see

```
   Compiling lens-rs v0.3.2 (.../repos/lens-rs/lens-rs)
 error[E0583]: file not found for module `dyn_optics`
   --> lens-rs/src/lib.rs:210:1
    |
210 | pub mod dyn_optics;
    | ^^^^^^^^^^^^^^^^^^^
    |
    = help: to create the module `dyn_optics`, create file "lens-rs/src/dyn_optics.rs" or "lens-rs/src/dyn_optics/mod.rs"

```
It looks like the recent merge added line 210 above, but not the dyn_optics.rs file.
Thanks for this crate!

**Comment by TOETOE55** [comment]
Oh sry, It was a dirty commit. I will fix it tomorrow ~

**Comment by TOETOE55** [comment]
Fixed.

**Comment by windwardly** [comment]
Thanks, and it looks like fix is in the dyn_lens branch and master still doesn't build.

**Comment by windwardly** [comment]
The fix was done in a branch and not master, so master still doesn't compile.
